/vl_vision:
  ros__parameters:
    # device: cpu
    inference_hz: 3.0
    image_topic: /camera/image_raw
    color_image_topic: /camera/camera/color/image_raw
    depth_image_topic: /camera/camera/aligned_depth_to_color/image_raw
    camera_info: /camera/camera/color/camera_info
    # GroundingDINO
    # grounding_dino_model_id: "IDEA-Research/grounding-dino-tiny"
    box_threshold: 0.35
    text_threshold: 0.25
    text_prompt: "Go to the blue backpack."