/vl_vision:
  ros__parameters:
    # device: cpu
    inference_hz: 1.0
    image_topic: /camera/image_raw
    color_image_topic: /camera/camera/color/image_raw
    depth_image_topic: /camera/camera/aligned_depth_to_color/image_raw
    camera_info: /camera/camera/color/camera_info
    # GroundingDINO
    # grounding_dino_model_id: "IDEA-Research/grounding-dino-tiny"
    box_threshold: 0.35
    text_threshold: 0.25
    text_prompt: "a person. a door. a chair. a backpack. a table. a trash can."
    # CLIP
    # clip_model_id: "openai/clip-vit-base-patch32"
    # clip_top_k: 1
    # clip_labels:
    #   - "a person"
    #   - "a door"
    #   - "an open door"
    #   - "a closed door"
    #   - "a chair"
    #   - "a table"
    #   - "a couch"
    #   - "a backpack"
    #   - "a laptop"
    #   - "a bottle"
    #   - "a trash can"
    #   - "a suitcase"
    #   - "a cabinet"
    #   - "a stairway"